#!/usr/bin/env bash

for f in Formula/*
do
  checksum=$(brew fetch --formula --quiet "$f" 2>/dev/null | cut -d ":" -f 2 | tr -d " ")
  echo "$f $checksum"
  sed -i '' "s/sha256.*/sha256 \"$checksum\"/" "$f"
done

for c in Casks/*
do
  # Skip unused cask
  if [ "$c" = "Casks/crossover211.rb" ]
  then
    continue
  fi

  checksum=$(brew fetch --cask --quiet "$c" 2>/dev/null | cut -d ":" -f 2 | tr -d " ")
  echo "$c $checksum"
  sed -i '' "s/sha256.*/sha256 \"$checksum\"/" "$c"
done
